In [5]:
import numpy as np


In [7]:
#1-d Array
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [9]:
type(arr1)

numpy.ndarray

In [15]:
arr2=np.array([1,2,3,4,5,6,7])
print(arr2[1:5])

[2 3 4 5]


In [17]:
arr3=np.array([1,2,3,4,5,6,7])
print(arr3[4:])

[5 6 7]


In [19]:
arr4=np.array([1,2,3,4,5,6,7])
print(arr4[1:5:2])

[2 4]
